## for a single neuron

In [ ]:
# implementing forward pass , loss calculation , backward pass and update rule on a single neuron which takes 3 inputs , has 2 weights and a bias

import numpy as np
inputs = np.array([1.0,-2.0,3.0])
weights = np.array([-3.0,-1.0,2.0])
bias = 1.0
target_output = 0
lr = 0.001


def relu(x):
  return np.maximum(0,x)

def relu_derivative(x):
  if x > 0 :
    return 1
  else:
    return 0

for i in range(200):
  #forward pass
  linear_output = inputs@weights.T+bias
  output = relu(linear_output)
  loss = (output-target_output)**2

  # backward pass
  # dloss/dweights = dloss/dweightedsum * dweightedsum/dweights
  dloss_doutput = 2*(output-target_output)
  doutput_dlinear = relu_derivative(linear_output)
  dlinear_dweights = inputs
  dlinear_dbias = 1

  dloss_dlinear = dloss_doutput*doutput_dlinear
  dloss_dweights = dloss_dlinear*dlinear_dweights
  dloss_dbias = dloss_dlinear*dlinear_dbias

  # update rule
  weights -= lr*dloss_dweights
  bias -= lr*dloss_dbias

  print(f"iteration {i+1},Loss: {loss}")
print("final_weights",weights)
print("final_bias",bias)

iteration 1,Loss: 36.0
iteration 2,Loss: 33.872399999999985
iteration 3,Loss: 31.870541159999995
iteration 4,Loss: 29.98699217744401
iteration 5,Loss: 28.21476093975706
iteration 6,Loss: 26.54726856821742
iteration 7,Loss: 24.978324995835766
iteration 8,Loss: 23.502105988581878
iteration 9,Loss: 22.113131524656684
iteration 10,Loss: 20.80624545154949
iteration 11,Loss: 19.576596345362915
iteration 12,Loss: 18.419619501351963
iteration 13,Loss: 17.331019988822064
iteration 14,Loss: 16.306756707482677
iteration 15,Loss: 15.343027386070442
iteration 16,Loss: 14.43625446755368
iteration 17,Loss: 13.583071828521268
iteration 18,Loss: 12.780312283455652
iteration 19,Loss: 12.024995827503426
iteration 20,Loss: 11.314318574097976
iteration 21,Loss: 10.645642346368787
iteration 22,Loss: 10.016484883698395
iteration 23,Loss: 9.424510627071816
iteration 24,Loss: 8.867522049011871
iteration 25,Loss: 8.34345149591527
iteration 26,Loss: 7.850353512506679
iteration 27,Loss: 7.386397619917536
iteratio

### implementing forward pass , loss calculation , backward pass and update rule on a neural network (layers formed by stacking the neurons)

In [ ]:
import numpy as np
inputs = np.array([1,2,3,4])
weights = np.array([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8],[0.9,1.0,1.1,1.2]])

bias = np.array([0.1,0.2,0.3])
lr = 0.001
target_output =0

def relu(x):
  return np.maximum(x,0)

def relu_derivative(x):
  return np.where(x>0,1,0)

for i in range(200):
  # forward pass
  z= inputs@weights.T+bias
  a = relu(z)
  y = np.sum(a)
  # loss
  loss = (y)**2

  # backward pass
  # dloss_dw = dloss/dy *dy/da* da/dz * dz/dw
  # this can be split as : dloss/dw  =  dl/dz * dz/dw
  dl_dy = 2*y
  dy_da = 1
  dl_da = dl_dy*dy_da

  da_dz = relu_derivative(z)

  dl_dz = dl_da * da_dz
  # dloss/dw  =  dl/dz * dz/dw
  dl_dw = np.outer(dl_dz,inputs)
  dl_db = dl_dz

  weights -=  lr*dl_dw
  bias -= lr*dl_db

  if i%20 == 0 :
    print(f"iteration : {i} and loss : {loss}")

print("final weights ",weights)
print("final_bais",bias)


iteration : 0 and loss : 466.56000000000006
iteration : 20 and loss : 5.32959636083938
iteration : 40 and loss : 0.41191523404899866
iteration : 60 and loss : 0.031836212079467595
iteration : 80 and loss : 0.002460565465389601
iteration : 100 and loss : 0.000190172825660145
iteration : 120 and loss : 1.4698126966451542e-05
iteration : 140 and loss : 1.1359926717815175e-06
iteration : 160 and loss : 8.779889800154524e-08
iteration : 180 and loss : 6.7858241357822796e-09
final weights  [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548461  0.27096922  0.00645383 -0.25806156]]
final_bais [-0.00698895 -0.04024714 -0.06451539]


## in the previous backpropagation for a layer of neurons , we did the derivatives manually for finding the gradients , this is not possible for multiple neurons having multiple layers , hence we will use matrices for the operations to find the gradients and the dLoss / dx


In [ ]:
import numpy as np

# considering dl_dz matrix is given
dl_dz = np.array([[1.,1.,1.],
[2.,2.,2.],
[3.,3.,3.]])

# the input array
inputs = np.array([[1.,2.,3.,2.5],[2.,5.,-1.,2.],[-1.5,2.7,3.3,-0.8]])    # 3 batches having 4 inputs each

# the weight matrix is given as dot product of the input's transpose with the dl_dz ,matrix
dLoss_dweights =  inputs.T@dl_dz

# 4x3 dot 3x3 : 4x3

print("gradients of weights with respect to the weights",dLoss_d_weights)


# calculating gradient of loss wrt biases
# is just the sum of the dloss_dz along the rows

dloss_dbias = np.sum(dl_dz,axis=0,keepdims=True)
print("gradient of the bias with respect to the weights",dloss_dbias)


# calculating the gradient of loss wrt inputs i.e DLoss_dinputs
# it is given by dot product of the dl_dz , weight_matrix's transpose
# here in this case of simple intuition
# we will consider the weight matrix already given

weights = np.array([[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,.87]]).T
dloss_dinputs = dl_dz@weights.T
print("gradients of weights with respect to the weights",dloss_dinputs)

gradients of weights with respect to the weights [[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]
gradient of the bias with respect to the weights [[6. 6. 6.]]
gradients of weights with respect to the weights [[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


# implementing as a class

In [ ]:
import numpy as np
class DenseLayer:
  def __init__(self,n_inputs,n_neurons) -> None:    # take the number of inputs and number of neurons in the layer
    self.weights = 0.01*np.random.randn(n_neurons,n_inputs)   # initialize weights with small random numbers , shape of weight matrix (n_neurons in current layer ,number of neurons in the previous layer)
    self.bias = np.zeros((1,n_neurons))  # initialize bias with 0

  def forwardpass(self,X):
    # weighted sum
    self.weighted_sum = X@self.weights.T+self.bias
    return self.weighted_sum

class ReLU:
  def forward(self,weighted_sum):
    return np.maximum(0,weighted_sum)

class SoftmaxCrossEntropy:
  def SoftMax_forward(self,weighted_sum):   # this makes the predictions : e^z1 / e^z1 + e^z2 + e^z3
    # subtract the maximum of each row from each number
    shifted = weighted_sum - np.max(weighted_sum ,axis =1 , keepdims = True)
    # get exponents of each value
    exp_weighted_sum = np.exp(shifted)
    return exp_weighted_sum / np.sum(exp_weighted_sum,axis=1,keepdims=True)

  def CC_forward(self,softmax_output,true_labels):    # this gets the loss : categorical cross entropy -> summation yilog(yi_hat)
    # convert the true_labels into one hot encoding if not given
    samples,classes = softmax_output.shape
    if len(true_labels.shape)==1:
      true_labels = np.eye(classes)[true_labels]
    # clip to prevent log(0)
    clipped = np.clip(softmax_output,1e-7,1-1e-7)
    corrected_confidence = np.sum(clipped*true_labels,axis=1)
    negative_log_likelihood = -np.log(corrected_confidence)
    return np.mean(negative_log_likelihood)

  def backward(self,y_true,y_pred):
    # partial differentiation of the loss wrt the weights (DL_Dz) is given by y_True-y_pred
    samples  = y_pred.shape[0]
    classes = y_pred.shape[1]
    if len(y_true.shape) == 1 : # ohe the true matrix , if not
      y_true = np.eye(classes)[y_true]
    Dloss_Dz = y_pred - y_true    # dloss_dz is the difference of the pred and true
    Dloss_Dz /= samples  # divide by number of samples to normalize
    return Dloss_Dz


In [ ]:


softmax_outputs  = np.array([[0.7,0.1,0.2],[0.1,0.5,0.4],[0.02,0.9,0.08]]) # y_pred
class_targets = np.array([0,1,1]) # y_true
sce = SoftmaxCrossEntropy()
# get loss
print(sce.CC_forward(softmax_outputs,class_targets))
# get DL/Dz
print(sce.backward(class_targets,softmax_outputs))

0.38506088005216804
[[-0.1         0.03333333  0.06666667]
 [ 0.03333333 -0.16666667  0.13333333]
 [ 0.00666667 -0.03333333  0.02666667]]
